# Generated by Django 5.2.4 on 2025-08-31 09:38

from django.db import migrations


def populate_counties(apps, schema_editor):
    """
    Data migration to populate County model with official 47 counties of Kenya
    """
    County = apps.get_model('scholarships', 'County')
    
    # Official 47 counties of Kenya with their details
    counties_data = [
        {
            'name': 'mombasa',
            'code': '001',
            'capital_city': 'Mombasa',
            'population': 1208333,
            'area_sq_km': 229.7
        },
        {
            'name': 'kwale',
            'code': '002',
            'capital_city': 'Kwale',
            'population': 866820,
            'area_sq_km': 8270.3
        },
        {
            'name': 'kilifi',
            'code': '003',
            'capital_city': 'Kilifi',
            'population': 1453787,
            'area_sq_km': 12245.9
        },
        {
            'name': 'tana_river',
            'code': '004',
            'capital_city': 'Hola',
            'population': 315943,
            'area_sq_km': 38437.0
        },
        {
            'name': 'lamu',
            'code': '005',
            'capital_city': 'Lamu',
            'population': 143920,
            'area_sq_km': 6167.2
        },
        {
            'name': 'taita_taveta',
            'code': '006',
            'capital_city': 'Voi',
            'population': 340671,
            'area_sq_km': 17083.9
        },
        {
            'name': 'garissa',
            'code': '007',
            'capital_city': 'Garissa',
            'population': 841353,
            'area_sq_km': 45720.2
        },
        {
            'name': 'wajir',
            'code': '008',
            'capital_city': 'Wajir',
            'population': 781263,
            'area_sq_km': 55840.6
        },
        {
            'name': 'mandera',
            'code': '009',
            'capital_city': 'Mandera',
            'population': 1025756,
            'area_sq_km': 26744.7
        },
        {
            'name': 'marsabit',
            'code': '010',
            'capital_city': 'Marsabit',
            'population': 459785,
            'area_sq_km': 61296.5
        },
        {
            'name': 'isiolo',
            'code': '011',
            'capital_city': 'Isiolo',
            'population': 268002,
            'area_sq_km': 25336.1
        },
        {
            'name': 'meru',
            'code': '012',
            'capital_city': 'Meru',
            'population': 1545714,
            'area_sq_km': 6930.1
        },
        {
            'name': 'tharaka_nithi',
            'code': '013',
            'capital_city': 'Chuka',
            'population': 393177,
            'area_sq_km': 2609.5
        },
        {
            'name': 'embu',
            'code': '014',
            'capital_city': 'Embu',
            'population': 608599,
            'area_sq_km': 2555.9
        },
        {
            'name': 'kitui',
            'code': '015',
            'capital_city': 'Kitui',
            'population': 1136187,
            'area_sq_km': 24385.1
        },
        {
            'name': 'machakos',
            'code': '016',
            'capital_city': 'Machakos',
            'population': 1421932,
            'area_sq_km': 5952.9
        },
        {
            'name': 'makueni',
            'code': '017',
            'capital_city': 'Wote',
            'population': 987653,
            'area_sq_km': 8008.9
        },
        {
            'name': 'nyandarua',
            'code': '018',
            'capital_city': 'Ol Kalou',
            'population': 673929,
            'area_sq_km': 3304.0
        },
        {
            'name': 'nyeri',
            'code': '019',
            'capital_city': 'Nyeri',
            'population': 759164,
            'area_sq_km': 2361.0
        },
        {
            'name': 'kirinyaga',
            'code': '020',
            'capital_city': 'Kerugoya',
            'population': 610411,
            'area_sq_km': 1205.4
        },
        {
            'name': 'murang\'a',
            'code': '021',
            'capital_city': 'Murang\'a',
            'population': 1056640,
            'area_sq_km': 2325.8
        },
        {
            'name': 'kiambu',
            'code': '022',
            'capital_city': 'Kiambu',
            'population': 2417735,
            'area_sq_km': 2449.2
        },
        {
            'name': 'turkana',
            'code': '023',
            'capital_city': 'Lodwar',
            'population': 926976,
            'area_sq_km': 71597.8
        },
        {
            'name': 'west_pokot',
            'code': '024',
            'capital_city': 'Kapenguria',
            'population': 621241,
            'area_sq_km': 9064.9
        },
        {
            'name': 'samburu',
            'code': '025',
            'capital_city': 'Maralal',
            'population': 310327,
            'area_sq_km': 20182.5
        },
        {
            'name': 'trans_nzoia',
            'code': '026',
            'capital_city': 'Kitale',
            'population': 990341,
            'area_sq_km': 2469.7
        },
        {
            'name': 'uasin_gishu',
            'code': '027',
            'capital_city': 'Eldoret',
            'population': 1163186,
            'area_sq_km': 2955.3
        },
        {
            'name': 'elgeyo_marakwet',
            'code': '028',
            'capital_city': 'Iten',
            'population': 454480,
            'area_sq_km': 3049.7
        },
        {
            'name': 'nandi',
            'code': '029',
            'capital_city': 'Kapsabet',
            'population': 885711,
            'area_sq_km': 2884.4
        },
        {
            'name': 'baringo',
            'code': '030',
            'capital_city': 'Kabarnet',
            'population': 666763,
            'area_sq_km': 11015.3
        },
        {
            'name': 'laikipia',
            'code': '031',
            'capital_city': 'Nanyuki',
            'population': 518560,
            'area_sq_km': 8696.1
        },
        {
            'name': 'nakuru',
            'code': '032',
            'capital_city': 'Nakuru',
            'population': 2162202,
            'area_sq_km': 7242.5
        },
        {
            'name': 'narok',
            'code': '033',
            'capital_city': 'Narok',
            'population': 1157873,
            'area_sq_km': 17944.1
        },
        {
            'name': 'kajiado',
            'code': '034',
            'capital_city': 'Kajiado',
            'population': 1117840,
            'area_sq_km': 21292.7
        },
        {
            'name': 'kericho',
            'code': '035',
            'capital_city': 'Kericho',
            'population': 901777,
            'area_sq_km': 2454.5
        },
        {
            'name': 'bomet',
            'code': '036',
            'capital_city': 'Bomet',
            'population': 875689,
            'area_sq_km': 1997.9
        },
        {
            'name': 'kakamega',
            'code': '037',
            'capital_city': 'Kakamega',
            'population': 1867579,
            'area_sq_km': 3224.5
        },
        {
            'name': 'vihiga',
            'code': '038',
            'capital_city': 'Vihiga',
            'population': 590013,
            'area_sq_km': 531.0
        },
        {
            'name': 'bungoma',
            'code': '039',
            'capital_city': 'Bungoma',
            'population': 1670570,
            'area_sq_km': 2206.9
        },
        {
            'name': 'busia',
            'code': '040',
            'capital_city': 'Busia',
            'population': 893681,
            'area_sq_km': 1628.4
        },
        {
            'name': 'siaya',
            'code': '041',
            'capital_city': 'Siaya',
            'population': 993183,
            'area_sq_km': 2496.1
        },
        {
            'name': 'kisumu',
            'code': '042',
            'capital_city': 'Kisumu',
            'population': 1155574,
            'area_sq_km': 2009.5
        },
        {
            'name': 'homa_bay',
            'code': '043',
            'capital_city': 'Homa Bay',
            'population': 1131950,
            'area_sq_km': 3154.7
        },
        {
            'name': 'migori',
            'code': '044',
            'capital_city': 'Migori',
            'population': 1116436,
            'area_sq_km': 2586.4
        },
        {
            'name': 'kisii',
            'code': '045',
            'capital_city': 'Kisii',
            'population': 1266860,
            'area_sq_km': 1318.0
        },
        {
            'name': 'nyamira',
            'code': '046',
            'capital_city': 'Nyamira',
            'population': 605576,
            'area_sq_km': 912.5
        },
        {
            'name': 'nairobi',
            'code': '047',
            'capital_city': 'Nairobi',
            'population': 4397073,
            'area_sq_km': 696.0
        },
    ]
    
    # Create county records
    created_counties = []
    for county_data in counties_data:
        county, created = County.objects.get_or_create(
            name=county_data['name'],
            defaults={
                'code': county_data['code'],
                'capital_city': county_data['capital_city'],
                'population': county_data['population'],
                'area_sq_km': county_data['area_sq_km']
            }
        )
        if created:
            created_counties.append(county.get_name_display())
    
    print(f"Successfully created {len(created_counties)} counties:")
    for county_name in created_counties:
        print(f"  - {county_name}")


def reverse_populate_counties(apps, schema_editor):
    """
    Reverse migration - delete all counties
    """
    County = apps.get_model('scholarships', 'County')
    County.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            populate_counties,
            reverse_populate_counties,
            hints={'model_name': 'county'}
        ),
    ]
