# Generated by Django 4.2.x on 2025-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20250831_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='source',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual Entry'),
                    ('scraper', 'Web Scraper'),
                    ('import', 'Data Import'),
                    ('api', 'API Integration'),
                ],
                default='manual',
                help_text='Source of this scholarship record',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='source_url',
            field=models.URLField(
                blank=True,
                help_text='Original URL if scraped from web'
            ),
        ),
    ]
